import campaignOne from "@/assets/ivora-campaign-01.jpg";
import campaignTwo from "@/assets/ivora-campaign-02.jpg";
import campaignThree from "@/assets/ivora-campaign-03.jpg";
import campaignFour from "@/assets/ivora-campaign-04.jpg";

export type Product = {
  id: string;
  name: string;
  slug: string;
  price: number;
  category: string;
  description: string;
  images: string[];
  colors: string[];
  sizes: string[];
  stock: number;
  tags: string[];
  featured: boolean;
  newArrival: boolean;
  bestSeller: boolean;
  mood: "Minimal" | "Street" | "Everyday" | "Elevated";
  fit: string;
  material: string;
  care: string;
};

export type Article = {
  slug: string;
  category: string;
  title: string;
  description: string;
  image: string;
};

export const campaignImages = {
  one: campaignOne,
  two: campaignTwo,
  three: campaignThree,
  four: campaignFour,
};

export const categories = ["Jackets", "T-Shirts", "Shirts", "Trousers", "Hoodies", "Sneakers", "Accessories"];
export const sizes = ["XS", "S", "M", "L", "XL", "XXL"];
export const colors = ["Ivory", "Black", "Sage", "Stone", "Charcoal", "Taupe"];
export const moods = ["Minimal", "Street", "Everyday", "Elevated"] as const;

const productDescriptions = {
  outer: "A refined IVORA essential cut for everyday ease, built around clean lines and quiet detail.",
  shirt: "A breathable staple with a considered drape, designed to move between weekday and evening settings.",
  trouser: "Relaxed tailoring with a polished finish, made for modern wardrobes and effortless pairing.",
  accessory: "A restrained IVORA finishing piece with a premium hand feel and everyday utility.",
};

export const products: Product[] = [
  {
    id: "ivr-001",
    name: "IVORA Signature Jacket",
    slug: "ivora-signature-jacket",
    price: 248,
    category: "Jackets",
    description: productDescriptions.outer,
    images: [campaignOne, campaignTwo, campaignThree],
    colors: ["Ivory", "Black", "Sage"],
    sizes,
    stock: 12,
    tags: ["jacket", "signature", "outerwear", "elevated", "minimal"],
    featured: true,
    newArrival: true,
    bestSeller: true,
    mood: "Elevated",
    fit: "Structured shoulders with a relaxed body and hip-length finish.",
    material: "Italian cotton twill blend with smooth viscose lining.",
    care: "Dry clean preferred. Steam lightly between wears.",
  },
  {
    id: "ivr-002",
    name: "IVORA Essential Oversized Tee",
    slug: "ivora-essential-oversized-tee",
    price: 68,
    category: "T-Shirts",
    description: productDescriptions.shirt,
    images: [campaignTwo, campaignFour, campaignOne],
    colors: ["Ivory", "Sage", "Black"],
    sizes,
    stock: 30,
    tags: ["tee", "t-shirt", "essential", "minimal", "everyday"],
    featured: true,
    newArrival: true,
    bestSeller: true,
    mood: "Everyday",
    fit: "Oversized through the body with a clean dropped shoulder.",
    material: "Heavyweight organic cotton jersey.",
    care: "Machine wash cold. Lay flat to dry.",
  },
  {
    id: "ivr-003",
    name: "IVORA Studio Shirt",
    slug: "ivora-studio-shirt",
    price: 128,
    category: "Shirts",
    description: productDescriptions.shirt,
    images: [campaignTwo, campaignOne, campaignFour],
    colors: ["Ivory", "Stone", "Sage"],
    sizes,
    stock: 18,
    tags: ["shirt", "studio", "work", "minimal"],
    featured: true,
    newArrival: true,
    bestSeller: false,
    mood: "Minimal",
    fit: "Relaxed tailoring with a soft collar and extended cuff.",
    material: "Cotton poplin with a subtle washed finish.",
    care: "Machine wash cold with similar colors.",
  },
  {
    id: "ivr-004",
    name: "IVORA Relaxed Cargo",
    slug: "ivora-relaxed-cargo",
    price: 158,
    category: "Trousers",
    description: productDescriptions.trouser,
    images: [campaignThree, campaignTwo, campaignFour],
    colors: ["Black", "Sage", "Stone"],
    sizes,
    stock: 7,
    tags: ["cargo", "trouser", "street", "relaxed"],
    featured: true,
    newArrival: true,
    bestSeller: false,
    mood: "Street",
    fit: "Mid-rise with a relaxed straight leg and utility pockets.",
    material: "Washed cotton nylon twill.",
    care: "Machine wash cold. Do not tumble dry.",
  },
  {
    id: "ivr-005",
    name: "IVORA Core Hoodie",
    slug: "ivora-core-hoodie",
    price: 138,
    category: "Hoodies",
    description: productDescriptions.outer,
    images: [campaignThree, campaignTwo, campaignOne],
    colors: ["Black", "Charcoal", "Sage"],
    sizes,
    stock: 21,
    tags: ["hoodie", "core", "street", "everyday"],
    featured: true,
    newArrival: false,
    bestSeller: true,
    mood: "Street",
    fit: "Relaxed hooded silhouette with a refined cropped hem.",
    material: "Brushed organic cotton fleece.",
    care: "Machine wash cold inside out.",
  },
  {
    id: "ivr-006",
    name: "IVORA Minimal Runner",
    slug: "ivora-minimal-runner",
    price: 182,
    category: "Sneakers",
    description: productDescriptions.accessory,
    images: [campaignFour, campaignThree, campaignTwo],
    colors: ["Ivory", "Stone", "Black"],
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44"],
    stock: 14,
    tags: ["sneaker", "runner", "minimal", "shoe"],
    featured: true,
    newArrival: false,
    bestSeller: true,
    mood: "Minimal",
    fit: "True to size with a cushioned low-profile sole.",
    material: "Suede, mesh, and smooth leather panels.",
    care: "Brush gently and spot clean only.",
  },
  {
    id: "ivr-007",
    name: "IVORA Everyday Trouser",
    slug: "ivora-everyday-trouser",
    price: 148,
    category: "Trousers",
    description: productDescriptions.trouser,
    images: [campaignTwo, campaignOne, campaignFour],
    colors: ["Stone", "Black", "Taupe"],
    sizes,
    stock: 24,
    tags: ["trouser", "everyday", "tailored", "elevated"],
    featured: true,
    newArrival: true,
    bestSeller: false,
    mood: "Everyday",
    fit: "Soft wide leg with pressed pleats and an easy waistband.",
    material: "Tencel wool blend with fluid drape.",
    care: "Dry clean or gentle cold wash.",
  },
  {
    id: "ivr-008",
    name: "IVORA Essential Overshirt",
    slug: "ivora-essential-overshirt",
    price: 176,
    category: "Shirts",
    description: productDescriptions.outer,
    images: [campaignFour, campaignTwo, campaignThree],
    colors: ["Sage", "Ivory", "Charcoal"],
    sizes,
    stock: 9,
    tags: ["overshirt", "shirt", "layer", "minimal"],
    featured: false,
    newArrival: true,
    bestSeller: false,
    mood: "Minimal",
    fit: "Boxy layer with dropped shoulders and clean patch pockets.",
    material: "Garment-dyed cotton canvas.",
    care: "Machine wash cold, reshape while damp.",
  },
  {
    id: "ivr-009",
    name: "IVORA Studio Jacket",
    slug: "ivora-studio-jacket",
    price: 268,
    category: "Jackets",
    description: productDescriptions.outer,
    images: [campaignThree, campaignOne, campaignTwo],
    colors: ["Black", "Stone"],
    sizes,
    stock: 4,
    tags: ["jacket", "studio", "street", "signature"],
    featured: true,
    newArrival: false,
    bestSeller: false,
    mood: "Street",
    fit: "Relaxed bomber shape with tonal hardware.",
    material: "Compact cotton sateen with light insulation.",
    care: "Dry clean only.",
  },
  {
    id: "ivr-010",
    name: "IVORA Core Tee",
    slug: "ivora-core-tee",
    price: 58,
    category: "T-Shirts",
    description: productDescriptions.shirt,
    images: [campaignFour, campaignTwo, campaignOne],
    colors: ["Ivory", "Black", "Taupe"],
    sizes,
    stock: 36,
    tags: ["tee", "core", "minimal", "basic"],
    featured: false,
    newArrival: false,
    bestSeller: true,
    mood: "Minimal",
    fit: "Regular fit with a straight hem and rib neck.",
    material: "Compact organic cotton jersey.",
    care: "Machine wash cold.",
  },
  {
    id: "ivr-011",
    name: "IVORA Relaxed Trouser",
    slug: "ivora-relaxed-trouser",
    price: 154,
    category: "Trousers",
    description: productDescriptions.trouser,
    images: [campaignOne, campaignTwo, campaignThree],
    colors: ["Ivory", "Stone", "Black"],
    sizes,
    stock: 16,
    tags: ["trouser", "relaxed", "signature", "elevated"],
    featured: true,
    newArrival: true,
    bestSeller: true,
    mood: "Elevated",
    fit: "Relaxed wide leg with tailored waistband.",
    material: "Cotton wool blend with smooth finish.",
    care: "Dry clean for best shape retention.",
  },
  {
    id: "ivr-012",
    name: "IVORA Soft Rib Tank",
    slug: "ivora-soft-rib-tank",
    price: 52,
    category: "T-Shirts",
    description: productDescriptions.shirt,
    images: [campaignTwo, campaignFour, campaignOne],
    colors: ["Ivory", "Black", "Sage"],
    sizes,
    stock: 28,
    tags: ["tank", "rib", "minimal", "summer"],
    featured: false,
    newArrival: true,
    bestSeller: false,
    mood: "Everyday",
    fit: "Close fit with soft stretch and a clean neckline.",
    material: "Organic cotton rib with elastane.",
    care: "Machine wash cold in garment bag.",
  },
  {
    id: "ivr-013",
    name: "IVORA Column Skirt",
    slug: "ivora-column-skirt",
    price: 132,
    category: "Trousers",
    description: productDescriptions.trouser,
    images: [campaignOne, campaignTwo, campaignFour],
    colors: ["Black", "Taupe"],
    sizes,
    stock: 10,
    tags: ["skirt", "column", "elevated", "minimal"],
    featured: false,
    newArrival: false,
    bestSeller: false,
    mood: "Elevated",
    fit: "Straight column fit with back vent for movement.",
    material: "Soft tailoring twill.",
    care: "Dry clean only.",
  },
  {
    id: "ivr-014",
    name: "IVORA Utility Tote",
    slug: "ivora-utility-tote",
    price: 118,
    category: "Accessories",
    description: productDescriptions.accessory,
    images: [campaignFour, campaignTwo, campaignThree],
    colors: ["Sage", "Black", "Stone"],
    sizes: ["ONE SIZE"],
    stock: 20,
    tags: ["tote", "bag", "accessory", "everyday"],
    featured: true,
    newArrival: false,
    bestSeller: true,
    mood: "Everyday",
    fit: "Spacious daily tote with internal slip pocket.",
    material: "Cotton canvas with leather handles.",
    care: "Spot clean with a soft cloth.",
  },
  {
    id: "ivr-015",
    name: "IVORA Tailored Vest",
    slug: "ivora-tailored-vest",
    price: 146,
    category: "Jackets",
    description: productDescriptions.outer,
    images: [campaignOne, campaignTwo, campaignFour],
    colors: ["Ivory", "Black"],
    sizes,
    stock: 8,
    tags: ["vest", "tailored", "elevated", "minimal"],
    featured: false,
    newArrival: true,
    bestSeller: false,
    mood: "Elevated",
    fit: "Slim tailored body designed for layering.",
    material: "Wool blend suiting with viscose lining.",
    care: "Dry clean only.",
  },
  {
    id: "ivr-016",
    name: "IVORA Draped Shirt",
    slug: "ivora-draped-shirt",
    price: 136,
    category: "Shirts",
    description: productDescriptions.shirt,
    images: [campaignTwo, campaignOne, campaignThree],
    colors: ["Ivory", "Taupe", "Sage"],
    sizes,
    stock: 11,
    tags: ["shirt", "draped", "elevated", "essential"],
    featured: false,
    newArrival: false,
    bestSeller: false,
    mood: "Elevated",
    fit: "Fluid relaxed silhouette with extended back hem.",
    material: "Tencel voile with a soft hand.",
    care: "Hand wash cold or dry clean.",
  },
  {
    id: "ivr-017",
    name: "IVORA City Cap",
    slug: "ivora-city-cap",
    price: 48,
    category: "Accessories",
    description: productDescriptions.accessory,
    images: [campaignFour, campaignThree, campaignTwo],
    colors: ["Sage", "Black", "Ivory"],
    sizes: ["ONE SIZE"],
    stock: 25,
    tags: ["cap", "accessory", "street", "everyday"],
    featured: false,
    newArrival: true,
    bestSeller: false,
    mood: "Street",
    fit: "Adjustable low-profile cap.",
    material: "Washed cotton twill.",
    care: "Spot clean only.",
  },
  {
    id: "ivr-018",
    name: "IVORA Wide Leg Denim",
    slug: "ivora-wide-leg-denim",
    price: 168,
    category: "Trousers",
    description: productDescriptions.trouser,
    images: [campaignThree, campaignOne, campaignTwo],
    colors: ["Charcoal", "Black"],
    sizes,
    stock: 13,
    tags: ["denim", "trouser", "street", "everyday"],
    featured: false,
    newArrival: false,
    bestSeller: true,
    mood: "Street",
    fit: "High-rise wide leg with long inseam.",
    material: "Rigid organic cotton denim.",
    care: "Wash sparingly inside out.",
  },
  {
    id: "ivr-019",
    name: "IVORA Fine Knit Polo",
    slug: "ivora-fine-knit-polo",
    price: 118,
    category: "Shirts",
    description: productDescriptions.shirt,
    images: [campaignTwo, campaignFour, campaignOne],
    colors: ["Sage", "Ivory", "Black"],
    sizes,
    stock: 15,
    tags: ["knit", "polo", "everyday", "minimal"],
    featured: false,
    newArrival: false,
    bestSeller: false,
    mood: "Everyday",
    fit: "Slim relaxed knit with open collar.",
    material: "Cotton cashmere blend.",
    care: "Hand wash cold, dry flat.",
  },
  {
    id: "ivr-020",
    name: "IVORA Leather Belt",
    slug: "ivora-leather-belt",
    price: 78,
    category: "Accessories",
    description: productDescriptions.accessory,
    images: [campaignFour, campaignOne, campaignTwo],
    colors: ["Black", "Taupe"],
    sizes: ["S", "M", "L"],
    stock: 19,
    tags: ["belt", "accessory", "minimal", "elevated"],
    featured: false,
    newArrival: false,
    bestSeller: false,
    mood: "Minimal",
    fit: "Classic width with refined metal buckle.",
    material: "Full-grain leather.",
    care: "Wipe clean and condition occasionally.",
  },
  {
    id: "ivr-021",
    name: "IVORA Cloud Sneaker",
    slug: "ivora-cloud-sneaker",
    price: 196,
    category: "Sneakers",
    description: productDescriptions.accessory,
    images: [campaignFour, campaignTwo, campaignThree],
    colors: ["Ivory", "Sage"],
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44"],
    stock: 6,
    tags: ["sneaker", "shoe", "everyday", "runner"],
    featured: true,
    newArrival: true,
    bestSeller: false,
    mood: "Everyday",
    fit: "Soft cushioned sole with supportive upper.",
    material: "Leather, suede, and recycled mesh.",
    care: "Spot clean with a damp cloth.",
  },
];

export const articles: Article[] = [
  {
    slug: "style-oversized-jacket",
    category: "Styling",
    title: "How to Style an Oversized Jacket",
    description: "A restrained guide to proportion, layering and clean contrast.",
    image: campaignOne,
  },
  {
    slug: "modern-wardrobe",
    category: "Wardrobe",
    title: "Building a Modern Wardrobe",
    description: "The IVORA approach to pieces that hold their shape season after season.",
    image: campaignTwo,
  },
  {
    slug: "everyday-dressing",
    category: "Editorial",
    title: "The Art of Everyday Dressing",
    description: "Quiet silhouettes, tactile fabrics and the confidence of simplicity.",
    image: campaignThree,
  },
  {
    slug: "inside-aw26",
    category: "Collection",
    title: "Inside IVORA AW26",
    description: "A closer look at the muted palette and architectural lines behind the season.",
    image: campaignFour,
  },
  {
    slug: "tone-on-tone",
    category: "Guide",
    title: "The Power of Tone-on-Tone",
    description: "How ivory, stone, sage and black become a complete wardrobe language.",
    image: campaignOne,
  },
];

export const heroSlides = [
  {
    label: "IVORA AW26",
    headline: "THE NEW STANDARD.",
    product: "IVORA Signature Jacket",
    text: "A clean silhouette, refined for the pace of now.",
    cta: "EXPLORE COLLECTION",
    image: campaignOne,
    slug: "ivora-signature-jacket",
  },
  {
    label: "IVORA ESSENTIALS",
    headline: "EVERYDAY, ELEVATED.",
    product: "IVORA Essential Shirt",
    text: "Soft structure and modern restraint for everyday dressing.",
    cta: "SHOP ESSENTIALS",
    image: campaignTwo,
    slug: "ivora-studio-shirt",
  },
  {
    label: "IVORA SIGNATURE",
    headline: "MADE FOR THE MOMENT.",
    product: "IVORA Relaxed Trouser",
    text: "Tailored ease with a confident, contemporary line.",
    cta: "DISCOVER IVORA",
    image: campaignThree,
    slug: "ivora-relaxed-trouser",
  },
];

export function formatPrice(price: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(price);
}

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function recommendProducts(product: Product, limit = 4) {
  const ranked = products
    .filter((candidate) => candidate.id !== product.id)
    .map((candidate) => ({
      candidate,
      score: candidate.tags.filter((tag) => product.tags.includes(tag)).length + (candidate.mood === product.mood ? 2 : 0),
    }))
    .sort((a, b) => b.score - a.score || a.candidate.price - b.candidate.price)
    .map(({ candidate }) => candidate);
  return ranked.slice(0, limit);
}

export function productsForMood(mood: Product["mood"]) {
  return products.filter((product) => product.mood === mood).slice(0, 6);
}
